make:
	@gcc -c shaker_sort.c
	@gcc -c client.c
	@gcc -o prog *.o

select_sort:
	@gcc -c select_sort.c
	@gcc -c client.c
	@gcc -o prog *.o

insert_sort:
	@gcc -c insert_sort.c
	@gcc -c client.c
	@gcc -o prog *.o

bubble_sort:
	@gcc -c bubble_sort.c
	@gcc -c client.c
	@gcc -o prog *.o

shaker_sort:
	@gcc -c select_sort.c
	@gcc -c client.c
	@gcc -o prog *.o

clean:
	@rm *.o
	@rm prog